// ─── Pull-request creation — host-agnostic so the daemon can ship, not just the IDE ───
//
// This logic used to live inside `createPRFromRun` in extension.ts, which meant an
// unattended run could do a night of work and then have no way to deliver it. The
// body-building is pure and the `gh` call is injected, so the same code backs the
// VS Code command and `moag run --pr` with identical output.

import { ghSync } from './gh';

/** One task's outcome, as it appears in the PR body checklist. */
export interface PrTaskOutcome {
  name: string;
  completed: boolean;
}

/** Everything needed to open a PR. No VS Code types, no module state. */
export interface PrRequest {
  cwd: string;
  title: string;
  planName: string;
  tasks: PrTaskOutcome[];
  changedFiles: string[];
  /** Optional target branch; `gh` picks the repo default when omitted. */
  base?: string;
  draft?: boolean;
}

/**
 * Why a PR could not be opened. Closed set — a new member must be handled at
 * every call site that reports it to a human.
 */
export type PrFailureReason = 'gh-missing' | 'no-commits' | 'failed';

export type PrOutcome =
  | { ok: true; url: string }
  | { ok: false; reason: PrFailureReason; message: string };

/** The injectable `gh` runner. Matches `ghSync`'s shape. */
export type GhRunner = (args: string[], opts?: { cwd?: string; timeout?: number }) => string;

const GH_INSTALL_HINT = 'Install the GitHub CLI to open PRs automatically: https://cli.github.com';

/** True when `gh` is on PATH and runnable. */
export function isGhAvailable(cwd: string, gh: GhRunner = ghSync): boolean {
  try {
    gh(['--version'], { cwd, timeout: 5000 });
    return true;
  } catch {
    return false;
  }
}

/**
 * Render the PR body. Pure — every input is passed in, so the same body can be
 * asserted in a unit test without touching git or the network.
 */
export function buildPrBody(
  req: Pick<PrRequest, 'planName' | 'tasks' | 'changedFiles'>,
): string {
  const planName = req.planName.trim() || 'untitled';

  const taskList = req.tasks.length > 0
    ? req.tasks.map((t) => `- ${t.completed ? '✅' : '❌'} ${t.name}`).join('\n')
    : 'No tasks recorded for this run.';

  const files = req.changedFiles.length > 0
    ? req.changedFiles.map((f) => `- \`${f}\``).join('\n')
    : 'No file changes detected.';

  return [
    '## Summary',
    `Generated by MOAG plan: "${planName}"`,
    '',
    '### Tasks',
    taskList,
    '',
    '### Changed Files',
    files,
    '',
    '---',
    '🤖 Generated with [MOAG](https://github.com/sujan-poudel-03/moag)',
  ].join('\n');
}

/** Map a `gh pr create` failure onto a reason a caller can act on. */
function classify(message: string): PrFailureReason {
  const m = message.toLowerCase();
  // `gh` says "no commits between main and <branch>" when the branch has nothing
  // to propose — by far the most common unattended failure, and the one with a
  // genuinely different remedy from a generic error.
  if (m.includes('no commits')) { return 'no-commits'; }
  return 'failed';
}

/**
 * Open a pull request for the work already committed in `cwd`.
 *
 * Note this proposes commits — it does not create them. Until the runner commits
 * per verified task, an unattended run on a clean branch resolves to
 * `{ ok: false, reason: 'no-commits' }`, which is the honest answer rather than
 * a silent success.
 */
export function createPullRequest(req: PrRequest, gh: GhRunner = ghSync): PrOutcome {
  if (!isGhAvailable(req.cwd, gh)) {
    return { ok: false, reason: 'gh-missing', message: GH_INSTALL_HINT };
  }

  const args = ['pr', 'create', '--title', req.title, '--body', buildPrBody(req)];
  if (req.base) { args.push('--base', req.base); }
  if (req.draft) { args.push('--draft'); }

  try {
    const out = gh(args, { cwd: req.cwd, timeout: 30000 });
    // `gh` prints progress lines before the URL; the URL is always last.
    const url = out.trim().split('\n').map((l) => l.trim()).filter(Boolean).pop() ?? '';
    return { ok: true, url };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { ok: false, reason: classify(message), message };
  }
}

/** A short, human-readable line for any failure reason. */
export function describeFailure(outcome: Extract<PrOutcome, { ok: false }>): string {
  switch (outcome.reason) {
    case 'gh-missing':
      return GH_INSTALL_HINT;
    case 'no-commits':
      return 'No commits on this branch to open a PR from. Commit the work first.';
    case 'failed':
      return `Failed to create PR: ${outcome.message.slice(0, 200)}`;
  }
}
